"""Add campaign table

Revision ID: 9f3471a15ecf
Revises: 8240886b63a1
Create Date: 2025-07-08 15:12:01.774720

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f3471a15ecf'
down_revision: Union[str, Sequence[str], None] = '8240886b63a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    'campaign',
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    # Add all new columns here directly
    sa.Column('template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_ids', sa.JSON(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('templateid', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('campaign', sa.Column('createdby', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('campaign', sa.Column('templatecontent', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('campaign', sa.Column('updatedat', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('campaign', sa.Column('contactids', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False))
    op.add_column('campaign', sa.Column('createdat', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('campaign', sa.Column('stats', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("json_build_object('total', 0, 'sent', 0, 'delivered', 0, 'read', 0, 'failed', 0)"), autoincrement=False, nullable=False))
    op.add_column('campaign', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False))
    op.add_column('campaign', sa.Column('scheduledat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('campaign', sa.Column('templatename', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('campaign', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('campaign', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('campaign', 'created_at')
    op.drop_column('campaign', 'created_by')
    op.drop_column('campaign', 'scheduled_at')
    op.drop_column('campaign', 'contact_ids')
    op.drop_column('campaign', 'language')
    op.drop_column('campaign', 'template_name')
    op.drop_column('campaign', 'template_id')
    op.create_table('messagetemplate',
    sa.Column('templateid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('language', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sub_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parameter_format', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('variables', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('messagetemplate_pkey'))
    )
    op.drop_table('template')
    # ### end Alembic commands ###
