"""Add run_payload to Campaign

Revision ID: d2421235d986
Revises: 9f3471a15ecf
Create Date: 2025-07-08 16:13:49.873875

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2421235d986'
down_revision: Union[str, Sequence[str], None] = '9f3471a15ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messagetemplate')
    op.add_column('campaign', sa.Column('components', sa.JSON(), nullable=True))
    op.add_column('campaign', sa.Column('run_payload', sa.JSON(), nullable=True))
    op.alter_column('campaign', 'id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('campaign', 'run_payload')
    op.drop_column('campaign', 'components')
    op.create_table('messagetemplate',
    sa.Column('templateid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('language', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sub_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parameter_format', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('variables', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('messagetemplate_pkey'))
    )
    # ### end Alembic commands ###
